---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # to push tags and create releases
      id-token: write    # to sign the attestation
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: '0'

      - name: Derive tag
        id: tag
        shell: bash
        run: |
          echo "ref_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Login to ghcr.io
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: startsWith(github.ref, 'refs/tags/')
        id: docker_build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          push: true
          provenance: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            docker.io/naishy/k8s-sidecar:latest
            docker.io/naishy/k8s-sidecar:${{ steps.tag.outputs.tag }}
            quay.io/naishy/k8s-sidecar:latest
            quay.io/naishy/k8s-sidecar:${{ steps.tag.outputs.tag }}
            ghcr.io/naishy/k8s-sidecar:latest
            ghcr.io/naishy/k8s-sidecar:${{ steps.tag.outputs.tag }}

      - name: Build Changelog
        if: startsWith(github.ref, 'refs/tags/')
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@439f79b5b5428107c7688c1d2b0e8bacc9b8792c # v6.0.1
        with:
          configuration: ".github/workflows/release-notes-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b #v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.ref_name }}
          name: ${{ steps.tag.outputs.ref_name }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
          prerelease: false
