---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'Dockerfile'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # to push tags and create releases
      id-token: write    # to sign the attestation
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: tagging
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8 # 1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          INITIAL_VERSION: 1.0.0
          BRANCH_HISTORY: last
      - name: Set up QEMU
        if: steps.tagging.outputs.part != '' && steps.tagging.outputs.part != 'none'
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        if: steps.tagging.outputs.part != '' && steps.tagging.outputs.part != 'none'
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to DockerHub
        if: steps.tagging.outputs.part != '' && steps.tagging.outputs.part != 'none'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Quay.io
        if: steps.tagging.outputs.part != '' && steps.tagging.outputs.part != 'none'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_BOT_USERNAME }}
          password: ${{ secrets.QUAY_BOT_PASSWORD }}

      - name: Login to ghcr.io
        if: steps.tagging.outputs.part != '' && steps.tagging.outputs.part != 'none'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: steps.tagging.outputs.part != '' && steps.tagging.outputs.part != 'none'
        id: docker_build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          push: true
          provenance: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            docker.io/kiwigrid/k8s-sidecar:latest
            docker.io/kiwigrid/k8s-sidecar:${{ steps.tagging.outputs.new_tag }}
            quay.io/kiwigrid/k8s-sidecar:latest
            quay.io/kiwigrid/k8s-sidecar:${{ steps.tagging.outputs.new_tag }}
            ghcr.io/kiwigrid/k8s-sidecar:latest
            ghcr.io/kiwigrid/k8s-sidecar:${{ steps.tagging.outputs.new_tag }}

      - name: Build Changelog
        if: steps.tagging.outputs.part != '' && steps.tagging.outputs.part != 'none'
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@439f79b5b5428107c7688c1d2b0e8bacc9b8792c # v6.0.1
        with:
          configuration: ".github/workflows/release-notes-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: steps.tagging.outputs.part != '' && steps.tagging.outputs.part != 'none'
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b #v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagging.outputs.new_tag }}
          name: v${{ steps.tagging.outputs.new_tag }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
          prerelease: false
