name: Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: tagging
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: none
      -
        name: "Set up QEMU"
        if: steps.tagging.outputs.part
        uses: docker/setup-qemu-action@v2
      -
        name: "Set up Docker Buildx"
        if: steps.tagging.outputs.part
        uses: docker/setup-buildx-action@v1
      -
        name: "Login to DockerHub"
        if: steps.tagging.outputs.part
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: "Login to Quay.io"
        if: steps.tagging.outputs.part
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_BOT_USERNAME }}
          password: ${{ secrets.QUAY_BOT_PASSWORD }}
      -
        name: "Build and push"
        if: steps.tagging.outputs.part
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
          tags: |
            docker.io/kiwigrid/k8s-sidecar:latest
            docker.io/kiwigrid/k8s-sidecar:${{ steps.tagging.outputs.tag }}
            quay.io/kiwigrid/k8s-sidecar:latest
            quay.io/kiwigrid/k8s-sidecar:${{ steps.tagging.outputs.tag }}
      - name: "Build Changelog"
        if: steps.tagging.outputs.part
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: ".github/workflows/release-notes-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Create Github Release"
        if: steps.tagging.outputs.part
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.tagging.outputs.tag }}
          release_name: v${{ steps.tagging.outputs.tag }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
          prerelease: false
